name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/chenyl8848/great-open-source-project.git
          git fetch upstream
          git merge --ff-only upstream/master
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
